tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "ochre-discovery": "#D4A017",
        "secondary-fixed-dim": "#adcfae",
        "azure-logic": "#4A6FA5",
        "on-primary-container": "#ff887f",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#410003",
        "tertiary": "#362600",
        "ink-black": "#000000",
        "on-secondary-container": "#4c6c50",
        "inverse-primary": "#ffb3ad",
        "on-primary-fixed-variant": "#852221",
        "surface-bright": "#fff8f1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdfa0",
        "on-surface": "#211b0b",
        "primary-container": "#7a1a1a",
        "error-container": "#ffdad6",
        "background": "#fff8f1",
        "surface-dim": "#e5d9bf",
        "surface-container-high": "#f4e7cc",
        "surface-container-low": "#fff2d9",
        "on-error": "#ffffff",
        "surface-container": "#faedd2",
        "on-tertiary-fixed": "#261a00",
        "outline-variant": "#dec0bd",
        "primary": "#5a0107",
        "on-tertiary-container": "#d6a21a",
        "primary-fixed-dim": "#ffb3ad",
        "inverse-on-surface": "#fdf0d5",
        "surface": "#fff8f1",
        "secondary-fixed": "#c8ecc9",
        "crimson-authority": "#7A1A1A",
        "on-background": "#211b0b",
        "outline": "#8a716f",
        "on-primary": "#ffffff",
        "forest-intellect": "#2D4B32",
        "secondary": "#47664b",
        "error": "#ba1a1a",
        "on-surface-variant": "#574240",
        "secondary-container": "#c8ecc9",
        "surface-tint": "#a53a36",
        "parchment-deep": "#F5D6A0",
        "surface-variant": "#eee1c7",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#eee1c7",
        "inverse-surface": "#37301e",
        "on-tertiary-fixed-variant": "#5c4300",
        "tertiary-container": "#523b00",
        "on-secondary-fixed-variant": "#2f4d34",
        "tertiary-fixed-dim": "#f6be39",
        "primary-fixed": "#ffdad6",
        "on-secondary-fixed": "#03210c",
        "parchment-base": "#FCEFD4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "grid-margin": "48px",
        "hairline": "0.5px",
        "accent-stroke": "2px",
        "section-gap": "80px",
        "grid-gutter": "24px"
      },
      fontFamily: {
        "headline-lg": ["Newsreader", "serif"],
        "body-md": ["Libre Franklin", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "body-lg": ["Libre Franklin", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "technical-sm": ["JetBrains Mono", "monospace"],
        "headline-display": ["Newsreader", "serif"]
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-lg-mobile": ["36px", { "lineHeight": "44px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "technical-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-display": ["84px", { "lineHeight": "92px", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    }
  }
}
